import { StyleSheet } from 'react-native';

export const authStyles = StyleSheet.create({
  authPage: {
    alignSelf: 'center',
    flexGrow: 1,
    justifyContent: 'center',
    maxWidth: 460,
    paddingVertical: 8,
    width: '100%',
  },
  authScrollContent: {
    alignItems: 'center',
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 32,
  },
  authCard: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    elevation: 4,
    padding: 16,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    width: '100%',
  },
  narrowAuthCard: {
    alignItems: 'center',
    maxWidth: 350,
  },
  authLogo: {
    alignSelf: 'center',
    height: 76,
    marginBottom: 16,
    width: 180,
  },
  authTextLogo: {
    color: '#ffcc00',
    fontSize: 24,
    fontWeight: '700',
  },
  authTitle: {
    color: '#222222',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
    textAlign: 'center',
  },
  authForm: {
    width: '100%',
  },
  authInput: {
    backgroundColor: '#ffffff',
    borderColor: '#ced4da',
    borderRadius: 6,
    borderWidth: 1,
    color: '#222222',
    fontSize: 15,
    marginBottom: 8,
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 10,
    width: '100%',
  },
  authPasswordRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 8,
  },
  authPasswordInput: {
    backgroundColor: '#ffffff',
    borderBottomLeftRadius: 6,
    borderColor: '#ced4da',
    borderRightWidth: 0,
    borderTopLeftRadius: 6,
    borderWidth: 1,
    color: '#222222',
    flex: 1,
    fontSize: 15,
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  authPasswordToggle: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderBottomRightRadius: 6,
    borderColor: '#ced4da',
    borderTopRightRadius: 6,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  authPasswordToggleText: {
    color: '#0d6efd',
    fontSize: 14,
    fontWeight: '600',
  },
  authLinkText: {
    color: '#2563eb',
    fontWeight: '700',
  },
  authMessage: {
    color: '#b45309',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 10,
    textAlign: 'center',
  },
  authPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#ffcc00',
    borderRadius: 6,
    justifyContent: 'center',
    minHeight: 46,
    width: '100%',
  },
  authPrimaryButtonText: {
    color: '#000000',
    fontSize: 16,
    fontWeight: '600',
  },
  authFooterRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 14,
  },
  authFooterText: {
    color: '#222222',
    fontSize: 14,
  },
  authFooterLink: {
    color: '#0d6efd',
    fontSize: 14,
    fontWeight: '700',
  },
  authModalOverlay: {
    backgroundColor: 'rgba(0,0,0,0.45)',
    flex: 1,
    justifyContent: 'center',
    padding: 18,
  },
  authModalBox: {
    alignSelf: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    maxHeight: '85%',
    maxWidth: 560,
    padding: 18,
    width: '100%',
  },
  authLoginAsBox: {
    backgroundColor: '#000000',
    borderRadius: 6,
    marginBottom: 8,
    padding: 12,
  },
  authLoginAsTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
  },
  authRadioRow: {
    columnGap: 18,
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 10,
  },
  authRadioItem: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 32,
  },
  authRadioOuter: {
    alignItems: 'center',
    borderColor: '#ffffff',
    borderRadius: 9,
    borderWidth: 2,
    height: 18,
    justifyContent: 'center',
    marginRight: 6,
    width: 18,
  },
  authRadioInner: {
    backgroundColor: '#ffcc00',
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  authRadioText: {
    color: '#ffffff',
  },
  authForgotText: {
    color: '#2563eb',
    marginVertical: 8,
    textAlign: 'right',
  },
  authTermsText: {
    color: '#666666',
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 8,
    textAlign: 'center',
  },
  authDividerText: {
    color: '#555555',
    marginVertical: 10,
    textAlign: 'center',
  },
  authSecondaryButton: {
    alignItems: 'center',
    borderColor: '#dddddd',
    borderRadius: 6,
    borderWidth: 1,
    padding: 14,
  },
  authSecondaryButtonText: {
    color: '#111827',
    fontWeight: '700',
  },
  authRegisterText: {
    color: '#666666',
    marginTop: 14,
    textAlign: 'center',
  },
  authModalCloseButton: {
    alignSelf: 'flex-end',
    padding: 6,
  },
  authModalCloseText: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  authModalTitle: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 16,
    textAlign: 'center',
  },
  authModalHeading: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
    marginTop: 12,
  },
  authModalParagraph: {
    color: '#333333',
    fontSize: 14,
    lineHeight: 21,
  },
  authKeyboardContainer: {
    backgroundColor: '#f2f2f2',
    flex: 1,
  },
  authSuccessText: {
    color: '#198754',
    fontSize: 14,
    marginTop: 12,
    textAlign: 'center',
  },
  authRequiredText: {
    color: '#dc3545',
    fontSize: 14,
    marginTop: 12,
    textAlign: 'center',
  },
  authLogoContainer: {
    alignItems: 'center',
    marginBottom: 10,
  },
  authInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  authHalfInput: {
    flex: 1,
  },
  authSelectInput: {
    justifyContent: 'center',
  },
  authSelectText: {
    color: '#222222',
    fontSize: 15,
  },
  authPlaceholderText: {
    color: '#777777',
    fontSize: 15,
  },
  authLoadingContainer: {
    alignItems: 'center',
    marginBottom: 8,
    marginTop: 8,
  },
  authLoadingText: {
    color: '#0427df',
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
  },
  authDisabledButton: {
    opacity: 0.7,
  },
  authErrorContainer: {
    alignItems: 'center',
    marginTop: 12,
  },
  authErrorText: {
    color: '#dc3545',
    fontSize: 14,
    textAlign: 'center',
  },
  authResendButton: {
    alignItems: 'center',
    backgroundColor: '#0d6efd',
    borderRadius: 6,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 42,
    paddingHorizontal: 14,
  },
  authResendButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  authPickerOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  authPickerCard: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    maxWidth: 320,
    paddingVertical: 8,
    width: '100%',
  },
  authPickerOption: {
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  authPickerOptionText: {
    color: '#222222',
    fontSize: 16,
    textAlign: 'center',
  },
  centeredContent: {
    alignSelf: 'center',
    maxWidth: 460,
    width: '100%',
  },
  header: {
    marginBottom: 32,
  },
  brand: {
    color: '#7dd3fc',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 20,
  },
  title: {
    color: '#ffffff',
    fontSize: 34,
    fontWeight: '800',
    lineHeight: 40,
  },
  subtitle: {
    color: '#bed0e4',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 10,
  },
  form: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    padding: 20,
    shadowColor: '#07111f',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 8,
  },
  field: {
    marginBottom: 16,
  },
  label: {
    color: '#223047',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#f4f7fb',
    borderColor: '#d7e0ea',
    borderRadius: 8,
    borderWidth: 1,
    color: '#132033',
    fontSize: 16,
    height: 52,
    paddingHorizontal: 14,
  },
  passwordRow: {
    alignItems: 'center',
    backgroundColor: '#f4f7fb',
    borderColor: '#d7e0ea',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    height: 52,
  },
  passwordInput: {
    color: '#132033',
    flex: 1,
    fontSize: 16,
    height: '100%',
    paddingLeft: 14,
    paddingRight: 8,
  },
  passwordToggle: {
    alignItems: 'center',
    height: '100%',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  passwordToggleText: {
    color: '#2563eb',
    fontSize: 14,
    fontWeight: '700',
  },
  optionsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  rememberRow: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 36,
  },
  checkbox: {
    alignItems: 'center',
    borderColor: '#b8c5d6',
    borderRadius: 6,
    borderWidth: 1,
    height: 22,
    justifyContent: 'center',
    marginRight: 9,
    width: 22,
  },
  checkboxChecked: {
    backgroundColor: '#2563eb',
    borderColor: '#2563eb',
  },
  checkmark: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 18,
  },
  optionText: {
    color: '#46566b',
    fontSize: 14,
    fontWeight: '600',
  },
  linkText: {
    color: '#2563eb',
    fontSize: 14,
    fontWeight: '700',
  },
  message: {
    color: '#b45309',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 14,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#2563eb',
    borderRadius: 8,
    height: 54,
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  footerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 18,
  },
  footerText: {
    color: '#617086',
    fontSize: 14,
  },
  footerLink: {
    color: '#2563eb',
    fontSize: 14,
    fontWeight: '800',
  },
});
