export const categories = [
  { EventCategoryId: 1, ParentCategoryId: null, CategoryName: 'Running', CategoryCode: 'running', Logo: '🏃' },
  { EventCategoryId: 4, ParentCategoryId: null, CategoryName: 'Trail Running', CategoryCode: 'trail_running', Logo: '⛰️' },
  { EventCategoryId: 2, ParentCategoryId: null, CategoryName: 'Swimming', CategoryCode: 'swimming', Logo: '🏊' },
  { EventCategoryId: 3, ParentCategoryId: null, CategoryName: 'Cycling', CategoryCode: 'cycling', Logo: '🚴' },
  { EventCategoryId: 5, ParentCategoryId: null, CategoryName: 'Triathlon', CategoryCode: 'triathlon', Logo: '🏊‍♂️🚴‍♂️🏃‍♂️' },
  { EventCategoryId: 6, ParentCategoryId: null, CategoryName: 'Adventure Racing', CategoryCode: 'adventure_racing', Logo: '🏞️' },
  { EventCategoryId: 7, ParentCategoryId: null, CategoryName: 'Winter Sports', CategoryCode: 'winter_sports', Logo: '❄️' },
  { EventCategoryId: 8, ParentCategoryId: null, CategoryName: 'Obstacle Racing', CategoryCode: 'obstacle_racing', Logo: '💪' },
  { EventCategoryId: 9, ParentCategoryId: 1, CategoryName: 'Road Running', CategoryCode: 'road_running', Logo: '🏃‍♂️' },
  { EventCategoryId: 10, ParentCategoryId: 1, CategoryName: 'Track Running', CategoryCode: 'track_running', Logo: '🏃‍♀️' },
  { EventCategoryId: 11, ParentCategoryId: 1, CategoryName: 'Ultra Running', CategoryCode: 'ultra_running', Logo: '🏃‍♂️🏃‍♀️' },
  { EventCategoryId: 12, ParentCategoryId: 1, CategoryName: 'Vertical Running', CategoryCode: 'vertical_running', Logo: '🏃‍♂️🧗‍♂️' },
  { EventCategoryId: 13, ParentCategoryId: 2, CategoryName: 'Pool Swimming', CategoryCode: 'pool_swimming', Logo: '🏊‍♀️' },
  { EventCategoryId: 14, ParentCategoryId: 2, CategoryName: 'Open Water Swimming', CategoryCode: 'open_water_swimming', Logo: '🌊🏊‍♂️' },
  { EventCategoryId: 15, ParentCategoryId: 2, CategoryName: 'Ice Swimming', CategoryCode: 'ice_swimming', Logo: '❄️🏊' },
  { EventCategoryId: 16, ParentCategoryId: 3, CategoryName: 'Road Cycling', CategoryCode: 'road_cycling', Logo: '🚴‍♀️' },
  { EventCategoryId: 17, ParentCategoryId: 3, CategoryName: 'Mountain Biking', CategoryCode: 'mountain_biking', Logo: '🚵‍♂️' },
  { EventCategoryId: 18, ParentCategoryId: 3, CategoryName: 'Gravel Cycling', CategoryCode: 'gravel_cycling', Logo: '🚴‍♂️' },
  { EventCategoryId: 19, ParentCategoryId: 5, CategoryName: 'Sprint Triathlon', CategoryCode: 'sprint_triathlon', Logo: '🏊‍♂️🚴‍♂️🏃‍♂️' },
  { EventCategoryId: 20, ParentCategoryId: 5, CategoryName: 'Olympic Triathlon', CategoryCode: 'olympic_triathlon', Logo: '🏊‍♀️🚴‍♀️🏃‍♀️' },
  { EventCategoryId: 21, ParentCategoryId: 5, CategoryName: 'Half Ironman (70.3)', CategoryCode: 'half_ironman', Logo: '💪' },
  { EventCategoryId: 22, ParentCategoryId: 5, CategoryName: 'Full Ironman', CategoryCode: 'full_ironman', Logo: '🛠️' },
  { EventCategoryId: 23, ParentCategoryId: 5, CategoryName: 'Winter Triathlon', CategoryCode: 'winter_triathlon', Logo: '❄️🏊‍♂️🚴‍♂️🏃‍♂️' },
  { EventCategoryId: 24, ParentCategoryId: 6, CategoryName: 'Expedition Racing', CategoryCode: 'expedition_racing', Logo: '⛺️🏞️' },
  { EventCategoryId: 25, ParentCategoryId: 6, CategoryName: 'Adventure Duathlon', CategoryCode: 'adventure_duathlon', Logo: '🏃‍♂️🚴‍♀️' },
  { EventCategoryId: 26, ParentCategoryId: 7, CategoryName: 'Snowshoe Running', CategoryCode: 'snowshoe_running', Logo: '❄️🏃‍♂️' },
  { EventCategoryId: 27, ParentCategoryId: 7, CategoryName: 'Cross-Country Skiing', CategoryCode: 'cross_country_skiing', Logo: '🎿' },
  { EventCategoryId: 28, ParentCategoryId: 8, CategoryName: 'Spartan Race', CategoryCode: 'spartan_race', Logo: '🏆' },
  { EventCategoryId: 29, ParentCategoryId: 8, CategoryName: 'Tough Mudder', CategoryCode: 'tough_mudder', Logo: '💪' },
  { EventCategoryId: 30, ParentCategoryId: 4, CategoryName: 'Short Trail Races', CategoryCode: 'short_trail_races', Logo: '🌲🏃‍♂️' },
  { EventCategoryId: 31, ParentCategoryId: 4, CategoryName: 'Medium Trail Races', CategoryCode: 'medium_trail_races', Logo: '🏞️🏃' },
  { EventCategoryId: 32, ParentCategoryId: 4, CategoryName: 'Ultra Trail Races', CategoryCode: 'ultra_trail_races', Logo: '⛰️🏃‍♂️' },
  { EventCategoryId: 33, ParentCategoryId: 4, CategoryName: 'Vertical Trail Races', CategoryCode: 'vertical_trail_races', Logo: '🏔️🏃‍♀️' },
  { EventCategoryId: 34, ParentCategoryId: 4, CategoryName: 'Night Trail Races', CategoryCode: 'night_trail_races', Logo: '🌑🏃‍♂️' },
];

export interface AchievementBadge {
  achievementBadgeId: number;
  achievementBadgeName: string;
  badgeIcon: string;
  eventCategoryId: number;
  categoryName: string;
  categoryClass: string;
  generalDistance: number;
}

export const achievementBadges: AchievementBadge[] = [
  { achievementBadgeId: 1, achievementBadgeName: 'Marathon Finisher', badgeIcon: '🏃‍♂️', eventCategoryId: 1, categoryName: 'Running', categoryClass: 'running', generalDistance: 42.195 },
  { achievementBadgeId: 2, achievementBadgeName: 'Half Marathon Finisher', badgeIcon: '🏃', eventCategoryId: 1, categoryName: 'Running', categoryClass: 'running', generalDistance: 21.1 },
  { achievementBadgeId: 3, achievementBadgeName: 'Ultra Runner', badgeIcon: '🥵', eventCategoryId: 1, categoryName: 'Running', categoryClass: 'ul-running', generalDistance: 50 },
  { achievementBadgeId: 4, achievementBadgeName: 'Vertical Runner', badgeIcon: '⛰️', eventCategoryId: 1, categoryName: 'Running', categoryClass: 'running', generalDistance: 10 },
  { achievementBadgeId: 5, achievementBadgeName: 'Trail Finisher', badgeIcon: '🌲', eventCategoryId: 4, categoryName: 'Trail Running', categoryClass: 't-running', generalDistance: 20 },
  { achievementBadgeId: 6, achievementBadgeName: 'Mountain Trail Finisher', badgeIcon: '🏞️', eventCategoryId: 4, categoryName: 'Trail Running', categoryClass: 't-running', generalDistance: 30 },
  { achievementBadgeId: 7, achievementBadgeName: 'Sky Runner', badgeIcon: '🌄', eventCategoryId: 4, categoryName: 'Trail Running', categoryClass: 'running', generalDistance: 15 },
  { achievementBadgeId: 8, achievementBadgeName: 'Channel Swimmer', badgeIcon: '🌊', eventCategoryId: 2, categoryName: 'Swimming', categoryClass: 'swimming', generalDistance: 20 },
  { achievementBadgeId: 9, achievementBadgeName: 'Bangla Channel Swimmer', badgeIcon: '🇧🇩', eventCategoryId: 2, categoryName: 'Swimming', categoryClass: 'swimming', generalDistance: 16 },
  { achievementBadgeId: 10, achievementBadgeName: 'Open Water Swimmer', badgeIcon: '🏖️', eventCategoryId: 2, categoryName: 'Swimming', categoryClass: 'swimming', generalDistance: 5 },
  { achievementBadgeId: 11, achievementBadgeName: 'Gran Fondo Finisher', badgeIcon: '🚴‍♂️', eventCategoryId: 3, categoryName: 'Cycling', categoryClass: 'cycling', generalDistance: 120 },
  { achievementBadgeId: 12, achievementBadgeName: 'Century Ride', badgeIcon: '💯', eventCategoryId: 3, categoryName: 'Cycling', categoryClass: 'cycling', generalDistance: 100 },
  { achievementBadgeId: 13, achievementBadgeName: 'Mountain Biker', badgeIcon: '🚵', eventCategoryId: 3, categoryName: 'Cycling', categoryClass: 'cycling', generalDistance: 50 },
  { achievementBadgeId: 14, achievementBadgeName: 'Gravel Rider', badgeIcon: '🪨', eventCategoryId: 3, categoryName: 'Cycling', categoryClass: 'cycling', generalDistance: 60 },
  { achievementBadgeId: 15, achievementBadgeName: 'Half Ironman', badgeIcon: '🏊‍♀️🚴‍♂️🏃', eventCategoryId: 5, categoryName: 'Triathlon', categoryClass: 'triathlon', generalDistance: 0 },
  { achievementBadgeId: 16, achievementBadgeName: 'Ironman', badgeIcon: '🔥', eventCategoryId: 5, categoryName: 'Triathlon', categoryClass: 'triathlon', generalDistance: 0 },
  { achievementBadgeId: 17, achievementBadgeName: 'Triathlete', badgeIcon: '🏁', eventCategoryId: 5, categoryName: 'Triathlon', categoryClass: 'triathlon', generalDistance: 0 },
  { achievementBadgeId: 18, achievementBadgeName: 'Adventure Racer', badgeIcon: '🧭', eventCategoryId: 6, categoryName: 'Adventure Racing', categoryClass: 'adventureRacing', generalDistance: 100 },
  { achievementBadgeId: 19, achievementBadgeName: 'Expedition Racer', badgeIcon: '🎒', eventCategoryId: 6, categoryName: 'Adventure Racing', categoryClass: 'adventureRacing', generalDistance: 150 },
  { achievementBadgeId: 20, achievementBadgeName: 'Winter Hiker', badgeIcon: '❄️', eventCategoryId: 7, categoryName: 'Winter Sports', categoryClass: 'winterSports', generalDistance: 10 },
  { achievementBadgeId: 21, achievementBadgeName: 'Snowshoer', badgeIcon: '👣', eventCategoryId: 7, categoryName: 'Winter Sports', categoryClass: 'winterSports', generalDistance: 8 },
  { achievementBadgeId: 22, achievementBadgeName: 'Ski Tourer', badgeIcon: '⛷️', eventCategoryId: 7, categoryName: 'Winter Sports', categoryClass: 'winterSports', generalDistance: 20 },
  { achievementBadgeId: 23, achievementBadgeName: 'Spartan Racer', badgeIcon: '🛡️', eventCategoryId: 8, categoryName: 'Obstacle Racing', categoryClass: 'obstacelRacing', generalDistance: 13 },
  { achievementBadgeId: 24, achievementBadgeName: 'Tough Mudder', badgeIcon: '💪', eventCategoryId: 8, categoryName: 'Obstacle Racing', categoryClass: 'obstacelRacing', generalDistance: 15 },
  { achievementBadgeId: 25, achievementBadgeName: 'OCR Finisher', badgeIcon: '🧗‍♂️', eventCategoryId: 8, categoryName: 'Obstacle Racing', categoryClass: 'obstacelRacing', generalDistance: 12 },
];

export const sportsApplicationList = [
  { runningAppID: 1, appName: 'Strava', categoryClass: 'category-strava' },
  { runningAppID: 2, appName: 'Garmin Connect', categoryClass: 'category-garmin-connect' },
  { runningAppID: 3, appName: 'RunKeeper', categoryClass: 'category-runkeeper' },
  { runningAppID: 4, appName: 'Nike Run Club', categoryClass: 'category-nike-run-club' },
  { runningAppID: 5, appName: 'MapMyRun', categoryClass: 'category-mapmyrun' },
  { runningAppID: 6, appName: 'Garmin Connect IQ', categoryClass: 'category-garmin-connect-iq' },
  { runningAppID: 7, appName: 'Suunto App', categoryClass: 'category-suunto' },
  { runningAppID: 8, appName: 'Strava Metro', categoryClass: 'category-strava-metro' },
  { runningAppID: 9, appName: 'Polar Flow', categoryClass: 'category-polar-flow' },
  { runningAppID: 10, appName: 'Zwift', categoryClass: 'category-zwift' },
];

export const TAGS = [
  { tagId: 1, tagName: 'marathon', category: 'Running' },
  { tagId: 2, tagName: 'half-marathon', category: 'Running' },
  { tagId: 3, tagName: 'ultra-running', category: 'Running' },
  { tagId: 4, tagName: 'trail-running', category: 'Running' },
  { tagId: 5, tagName: 'running-technique', category: 'Running' },
  { tagId: 6, tagName: 'running-shoes', category: 'Running' },
  { tagId: 7, tagName: 'hydration', category: 'Running' },
  { tagId: 8, tagName: 'nutrition', category: 'Running' },
  { tagId: 9, tagName: 'injury-prevention', category: 'Running' },
  { tagId: 10, tagName: 'training-plan', category: 'Running' },
  { tagId: 11, tagName: 'interval-training', category: 'Running' },
  { tagId: 12, tagName: 'hill-training', category: 'Running' },
  { tagId: 13, tagName: 'recovery', category: 'Running' },
  { tagId: 14, tagName: 'race-day-strategy', category: 'Running' },
  { tagId: 15, tagName: 'warm-up', category: 'Running' },
  { tagId: 16, tagName: 'cool-down', category: 'Running' },
  { tagId: 17, tagName: 'road-cycling', category: 'Cycling' },
  { tagId: 18, tagName: 'mountain-biking', category: 'Cycling' },
  { tagId: 19, tagName: 'cycling-gear', category: 'Cycling' },
  { tagId: 20, tagName: 'cycling-shoes', category: 'Cycling' },
  { tagId: 21, tagName: 'bike-maintenance', category: 'Cycling' },
  { tagId: 22, tagName: 'bike-fitting', category: 'Cycling' },
  { tagId: 23, tagName: 'cycling-nutrition', category: 'Cycling' },
  { tagId: 24, tagName: 'cycling-technique', category: 'Cycling' },
  { tagId: 25, tagName: 'hill-climbing', category: 'Cycling' },
  { tagId: 26, tagName: 'cycling-races', category: 'Cycling' },
  { tagId: 27, tagName: 'cycling-endurance', category: 'Cycling' },
  { tagId: 28, tagName: 'cycling-training', category: 'Cycling' },
  { tagId: 29, tagName: 'cycling-recovery', category: 'Cycling' },
  { tagId: 30, tagName: 'cadence', category: 'Cycling' },
  { tagId: 31, tagName: 'cycling-injury-prevention', category: 'Cycling' },
  { tagId: 32, tagName: 'open-water-swimming', category: 'Swimming' },
  { tagId: 33, tagName: 'pool-training', category: 'Swimming' },
  { tagId: 34, tagName: 'swimming-technique', category: 'Swimming' },
  { tagId: 35, tagName: 'freestyle-swimming', category: 'Swimming' },
  { tagId: 36, tagName: 'breathing-technique', category: 'Swimming' },
  { tagId: 37, tagName: 'triathlon-swimming', category: 'Swimming' },
  { tagId: 38, tagName: 'swim-gear', category: 'Swimming' },
  { tagId: 39, tagName: 'wetsuits', category: 'Swimming' },
  { tagId: 40, tagName: 'swim-endurance', category: 'Swimming' },
  { tagId: 41, tagName: 'kick-training', category: 'Swimming' },
  { tagId: 42, tagName: 'stroke-efficiency', category: 'Swimming' },
  { tagId: 43, tagName: 'flip-turns', category: 'Swimming' },
  { tagId: 44, tagName: 'swim-drills', category: 'Swimming' },
  { tagId: 45, tagName: 'swim-recovery', category: 'Swimming' },
  { tagId: 46, tagName: 'smartwatch', category: 'General' },
  { tagId: 47, tagName: 'heart-rate-monitor', category: 'General' },
  { tagId: 48, tagName: 'gps-watch', category: 'General' },
  { tagId: 49, tagName: 'wearable-tech', category: 'General' },
  { tagId: 50, tagName: 'strength-training', category: 'General' },
  { tagId: 51, tagName: 'cross-training', category: 'General' },
  { tagId: 52, tagName: 'injury-recovery', category: 'General' },
  { tagId: 53, tagName: 'race-preparation', category: 'General' },
  { tagId: 54, tagName: 'mental-training', category: 'General' },
  { tagId: 55, tagName: 'sports-nutrition', category: 'Food & Diet' },
  { tagId: 56, tagName: 'race-day-nutrition', category: 'Food & Diet' },
  { tagId: 57, tagName: 'energy-gels', category: 'Food & Diet' },
  { tagId: 58, tagName: 'pre-race-meals', category: 'Food & Diet' },
  { tagId: 59, tagName: 'post-workout-meals', category: 'Food & Diet' },
  { tagId: 60, tagName: 'hydration-strategy', category: 'Food & Diet' },
  { tagId: 61, tagName: 'protein-intake', category: 'Food & Diet' },
  { tagId: 62, tagName: 'carb-loading', category: 'Food & Diet' },
  { tagId: 63, tagName: 'electrolytes', category: 'Food & Diet' },
  { tagId: 64, tagName: 'fat-adapted-training', category: 'Food & Diet' },
  { tagId: 65, tagName: 'vegan-athlete-diet', category: 'Food & Diet' },
  { tagId: 66, tagName: 'keto-for-athletes', category: 'Food & Diet' },
  { tagId: 67, tagName: 'endurance-fueling', category: 'Food & Diet' },
  { tagId: 68, tagName: 'healthy-snacks', category: 'Food & Diet' },
  { tagId: 69, tagName: 'meal-planning', category: 'Food & Diet' },
];

export const runningWebsites = [
  {
    FullName: 'International Trail Running Association',
    ShortName: 'ITRA',
    Website: 'https://itra.run',
    ShortDescription: 'Offers a global trail running race calendar, performance index, and certification for trail races.',
    WebsiteId: 1,
    className: 'bg-green-600 text-white',
    iconName: 'ITRA.jpg',
  },
  {
    FullName: 'UltraSignup',
    ShortName: 'UltraSignup',
    Website: 'https://ultrasignup.com',
    ShortDescription: 'A registration platform for trail and ultramarathon events, with rankings and results tracking.',
    WebsiteId: 2,
    className: 'bg-blue-500 text-white',
    iconName: 'UltraSignup.jpg',
  },
  {
    FullName: 'Trail Runner Magazine',
    ShortName: 'TrailRunner',
    Website: 'https://www.trailrunnermag.com',
    ShortDescription: 'Provides trail running news, training tips, gear reviews, and race reports.',
    WebsiteId: 3,
    className: 'bg-red-600 text-white',
    iconName: 'TrailRunner.jpg',
  },
  {
    FullName: 'SkyRunning',
    ShortName: 'SkyRunning',
    Website: 'https://www.skyrunning.com',
    ShortDescription: 'Focuses on mountain running events with steep terrains and high altitudes.',
    WebsiteId: 4,
    className: 'bg-gray-700 text-white',
    iconName: 'SkyRunning.jpg',
  },
  {
    FullName: 'Run Ultra',
    ShortName: 'RunUltra',
    Website: 'https://runultra.co.uk',
    ShortDescription: 'Features a global database of ultramarathon and trail running events, guides, and reviews.',
    WebsiteId: 5,
    className: 'bg-orange-600 text-white',
    iconName: 'RunUltra.jpg',
  },
  {
    FullName: 'Fastest Known Time',
    ShortName: 'FKT',
    Website: 'https://fastestknowntime.com',
    ShortDescription: 'Tracks the fastest times on trail routes globally, encouraging personal challenges and adventure running.',
    WebsiteId: 6,
    className: 'bg-yellow-500 text-black',
    iconName: 'FKT.jpg',
  },
  {
    FullName: 'UTMB World Series',
    ShortName: 'UTMB',
    Website: 'https://utmb.world',
    ShortDescription: 'Hosts information on the Ultra-Trail du Mont-Blanc and its international series of prestigious trail races.',
    WebsiteId: 7,
    className: 'bg-blue-800 text-white',
    iconName: 'UTMB.jpg',
  },
  {
    FullName: 'Trail Sisters',
    ShortName: 'TrailSisters',
    Website: 'https://trailsisters.net',
    ShortDescription: 'Empowers women in trail running through community, advice, and event information.',
    WebsiteId: 8,
    className: 'bg-pink-500 text-white',
    iconName: 'TrailSisters.jpg',
  },
  {
    FullName: 'American Trail Running Association',
    ShortName: 'ATRA',
    Website: 'https://trailrunner.com',
    ShortDescription: 'Advocates for trail running events and supports the U.S. trail running community.',
    WebsiteId: 9,
    className: 'bg-indigo-600 text-white',
    iconName: 'ATRA.jpg',
  },
  {
    FullName: 'Mud, Sweat & Tears',
    ShortName: 'MudSweatTears',
    Website: 'https://mudsweatandtears.co.uk',
    ShortDescription: 'UK-based platform for trail running news, gear reviews, and race updates.',
    WebsiteId: 10,
    className: 'bg-brown-600 text-white',
    iconName: 'MudSweatTears.jpg',
  },
  {
    FullName: 'Salomon Running',
    ShortName: 'Salomon',
    Website: 'https://www.salomonrunning.com',
    ShortDescription: 'Shares inspiration, event sponsorships, and athlete profiles from Salomon’s trail running team.',
    WebsiteId: 11,
    className: 'bg-red-500 text-white',
    iconName: 'Salomon.jpg',
  },
  {
    FullName: 'Trail Running UK',
    ShortName: 'TrailRunningUK',
    Website: 'https://www.trailrunning.co.uk',
    ShortDescription: 'A UK-centric website offering race guides, gear reviews, and tips for trail runners.',
    WebsiteId: 12,
    className: 'bg-green-500 text-white',
    iconName: 'TrailRunningUK.jpg',
  },
  {
    FullName: 'World Athletics',
    ShortName: 'WorldAthletics',
    Website: 'https://worldathletics.org',
    ShortDescription: 'The global governing body for athletics, including road running and marathons.',
    WebsiteId: 13,
    className: 'bg-blue-700 text-white',
    iconName: 'WorldAthletics.jpg',
  },
  {
    FullName: 'Marathon Guide',
    ShortName: 'MarathonGuide',
    Website: 'https://www.marathonguide.com',
    ShortDescription: 'Provides a comprehensive list of marathons worldwide, along with reviews and results.',
    WebsiteId: 14,
    className: 'bg-teal-500 text-white',
    iconName: 'MarathonGuide.jpg',
  },
  {
    FullName: 'Running USA',
    ShortName: 'RunningUSA',
    Website: 'https://www.runningusa.org',
    ShortDescription: 'A hub for the road running industry, offering insights, resources, and race listings.',
    WebsiteId: 15,
    className: 'bg-gray-600 text-white',
    iconName: 'RunningUSA.jpg',
  },
  {
    FullName: 'LetsRun',
    ShortName: 'LetsRun',
    Website: 'https://www.letsrun.com',
    ShortDescription: 'Popular for news, forums, and discussions about professional and amateur running events.',
    WebsiteId: 16,
    className: 'bg-orange-500 text-white',
    iconName: 'LetsRun.jpg',
  },
  {
    FullName: 'Boston Athletic Association (BAA)',
    ShortName: 'BAA',
    Website: 'https://www.baa.org',
    ShortDescription: 'Organizes the Boston Marathon and provides resources for marathon runners.',
    WebsiteId: 17,
    className: 'bg-blue-900 text-white',
    iconName: 'BAA.jpg',
  },
  {
    FullName: 'RunSignUp',
    ShortName: 'RunSignUp',
    Website: 'https://runsignup.com',
    ShortDescription: 'A registration platform for road running events, with race calendars and results tracking.',
    WebsiteId: 18,
    className: 'bg-purple-500 text-white',
    iconName: 'RunSignUp.jpg',
  },
  {
    FullName: 'Hal Higdon',
    ShortName: 'HalHigdon',
    Website: 'https://www.halhigdon.com',
    ShortDescription: 'Offers free training plans for road races, from 5Ks to marathons.',
    WebsiteId: 19,
    className: 'bg-yellow-400 text-black',
    iconName: 'HalHigdon.jpg',
  },
  {
    FullName: 'Runners World',
    ShortName: 'RunnersWorld',
    Website: 'https://www.runnersworld.com',
    ShortDescription: 'A leading publication for running news, training tips, and gear reviews for both road and trail runners.',
    WebsiteId: 20,
    className: 'bg-red-700 text-white',
    iconName: 'RunnersWorld.jpg',
  },
];

export const statusOptions = [
  { EventStatusId: 1, EventStatusName: 'Planning', color: 'blue' },
  { EventStatusId: 2, EventStatusName: 'Scheduled', color: '#188709' },
  { EventStatusId: 3, EventStatusName: 'Completed', color: 'black' },
  { EventStatusId: 4, EventStatusName: 'Cancelled', color: 'red' },
  { EventStatusId: 5, EventStatusName: 'Postponed', color: '#ffe5b4' },
  { EventStatusId: 6, EventStatusName: 'On Hold', color: '#795a5a' },
  { EventStatusId: 7, EventStatusName: 'Pending', color: '#d1c8ae' },
];

export const raceDistanceConstact = [
  0.1, 0.2, 0.4, 1, 1.5, 2, 3, 5, 7.5, 8, 10, 13, 16, 21, 25, 26,
  30, 33, 42, 50, 83, 100, 113, 160, 200, 226,
];
